### ISSUE TITLE
Don't use sudo on "make package install"

### ISSUE THREAD

**Issue by fritz-fritz** [kirb/theos#16]
For some reason sudo is being called when installing from OS X to iOS.

Since we are connecting as root there should be no need to call sudo. Currently, the install fails without sudo installed on the iOS device.

```
==> Installing…
sh: sudo: command not found
make: *** [internal-install] Error 127
```

Works fine if sudo is installed.

**Comment by brycedev** [comment]
I have also experienced this issue. I installed sudo on my device, but was still unable to install the package. 

My "fix" involved modifying $THEOS/makefiles/install/deb_remote.mk and removing the sudo command. 

from : 

```
$(ECHO_NOTHING)install.exec "cat > /tmp/_theos_install.deb; $(THEOS_SUDO_COMMAND) dpkg -i /tmp/_theos_install.deb && rm /tmp/_theos_install.deb" < "$(_THEOS_PACKAGE_LAST_FILENAME)"$(ECHO_END)
```

to : 

```
$(ECHO_NOTHING)install.exec "cat > /tmp/_theos_install.deb; dpkg -i /tmp/_theos_install.deb && rm /tmp/_theos_install.deb" < "$(_THEOS_PACKAGE_LAST_FILENAME)"$(ECHO_END)
```

This is bad because at some point if I update theos, I will lose the fix.

Kirb, can this modification be made by you since we shouldn't need to use sudo?

**Comment by kirb** [comment]
Really should have fixed this sooner, sorry. Done in e4b4789
